REWIRE ScanMode_ISO_U0_Z_ECO_10_U0/Z  u_pcs_sds/u_pcssds/pcs/lane_0/pcie_rx/fifo_init_prx_reg_CP_MUX_U0/S
REWIRE ScanMode_ISO_U0_Z_ECO_10_U0_Z_ALCHIP_110929_U0/Z u_pcs_sds/u_pcssds/pcs/lane_1/pcie_rx/fifo_init_prx_reg_CP_MUX_U0/S
REWIRE ScanMode_ISO_U0_Z_ECO_10_U0_Z_ALCHIP_110929_U0/Z u_pcs_sds/u_pcssds/pcs/lane_2/pcie_rx/fifo_init_prx_reg_CP_MUX_U0/S
REWIRE ScanMode_ISO_U0_Z_ECO_10_U0_Z_ALCHIP_110929_U0/Z u_pcs_sds/u_pcssds/pcs/lane_3/pcie_rx/fifo_init_prx_reg_CP_MUX_U0/S
