/* Milkyway Technology file generated by TechBuilder
   Metal Stack Option = tsmc_cln65gp_5x2z */

Technology	{
		name				= "tsmc_cln65gplus_adv12"
		dielectric			= 3.45e-05
		unitTimeName			= "ns"
		timePrecision			= 1000
		unitLengthName			= "micron"
		lengthPrecision			= 1000
		gridResolution			= 5
		unitVoltageName			= "v"
		voltagePrecision		= 1000000
		unitCurrentName			= "ma"
		currentPrecision		= 1000
		unitPowerName			= "mw"
		powerPrecision			= 100000
		unitResistanceName		= "kohm"
		resistancePrecision		= 10000000
		unitCapacitanceName		= "pf"
		capacitancePrecision		= 10000000
		unitInductanceName		= "nh"
		inductancePrecision		= 100
		minBaselineTemperature		= 25
		nomBaselineTemperature		= 25
		maxBaselineTemperature		= 25
		minEdgeMode			= 1
		stubMode			= 4
}

Tile		"unit" {
		width				= 0.2
		height				= 2.4
}

Layer		"PW" {
		layerNumber			= 2
		maskName			= ""
		visible				= 1
		selectable			= 1
		blink				= 0
		color				= "blue"
		lineStyle			= "solid"
		pattern				= "blank"
		pitch				= 0
		defaultWidth			= 0
		minWidth			= 0
		minSpacing			= 0
		endOfLineCornerKeepoutWidth	= 0
}

Layer		"NW" {
		layerNumber			= 3
		maskName			= ""
		visible				= 1
		selectable			= 1
		blink				= 0
		color				= "cyan"
		lineStyle			= "solid"
		pattern				= "blank"
		pitch				= 0
		defaultWidth			= 0
		minWidth			= 0
		minSpacing			= 0
		endOfLineCornerKeepoutWidth	= 0
}

LayerDataType		"NW_TEXT" {
		layerNumber			= 3
		dataTypeNumber			= 20
		visible				= 1
		selectable			= 1
		blink				= 0
		color				= "red"
		lineStyle			= "solid"
		pattern				= "blank"
}

Layer		"PM" {
		layerNumber			= 5
		maskName			= ""
		visible				= 1
		selectable			= 1
		blink				= 0
		color				= "green"
		lineStyle			= "solid"
		pattern				= "blank"
		pitch				= 0
		defaultWidth			= 0
		minWidth			= 0
		minSpacing			= 0
		endOfLineCornerKeepoutWidth	= 0
}

Layer		"OD" {
		layerNumber			= 6
		maskName			= ""
		visible				= 1
		selectable			= 1
		blink				= 0
		color				= "magenta"
		lineStyle			= "solid"
		pattern				= "blank"
		pitch				= 0
		defaultWidth			= 0
		minWidth			= 0
		minSpacing			= 0
		endOfLineCornerKeepoutWidth	= 0
}

LayerDataType		"OD_TEXT" {
		layerNumber			= 6
		dataTypeNumber			= 6
		visible				= 1
		selectable			= 1
		blink				= 0
		color				= "purple"
		lineStyle			= "solid"
		pattern				= "blank"
}

Layer		"PDIFF" {
		layerNumber			= 7
		maskName			= ""
		visible				= 1
		selectable			= 1
		blink				= 0
		color				= "white"
		lineStyle			= "solid"
		pattern				= "blank"
		pitch				= 0
		defaultWidth			= 0
		minWidth			= 0
		minSpacing			= 0
		endOfLineCornerKeepoutWidth	= 0
}

Layer		"NDIFF" {
		layerNumber			= 8
		maskName			= ""
		visible				= 1
		selectable			= 1
		blink				= 0
		color				= "yellow"
		lineStyle			= "solid"
		pattern				= "blank"
		pitch				= 0
		defaultWidth			= 0
		minWidth			= 0
		minSpacing			= 0
		endOfLineCornerKeepoutWidth	= 0
}

Layer		"NT_N" {
		layerNumber			= 11
		maskName			= ""
		visible				= 1
		selectable			= 1
		blink				= 0
		color				= "red"
		lineStyle			= "solid"
		pattern				= "blank"
		pitch				= 0
		defaultWidth			= 0
		minWidth			= 0
		minSpacing			= 0
		endOfLineCornerKeepoutWidth	= 0
}

Layer		"VTL_N" {
		layerNumber			= 12
		maskName			= ""
		visible				= 1
		selectable			= 1
		blink				= 0
		color				= "blue"
		lineStyle			= "solid"
		pattern				= "blank"
		pitch				= 0
		defaultWidth			= 0
		minWidth			= 0
		minSpacing			= 0
		endOfLineCornerKeepoutWidth	= 0
}

Layer		"VTL_P" {
		layerNumber			= 13
		maskName			= ""
		visible				= 1
		selectable			= 1
		blink				= 0
		color				= "cyan"
		lineStyle			= "solid"
		pattern				= "blank"
		pitch				= 0
		defaultWidth			= 0
		minWidth			= 0
		minSpacing			= 0
		endOfLineCornerKeepoutWidth	= 0
}

Layer		"OD_18" {
		layerNumber			= 16
		maskName			= ""
		visible				= 1
		selectable			= 1
		blink				= 0
		color				= "magenta"
		lineStyle			= "solid"
		pattern				= "blank"
		pitch				= 0
		defaultWidth			= 0
		minWidth			= 0
		minSpacing			= 0
		endOfLineCornerKeepoutWidth	= 0
}

Layer		"PO" {
		layerNumber			= 17
		maskName			= ""
		visible				= 1
		selectable			= 1
		blink				= 0
		color				= "green"
		lineStyle			= "solid"
		pattern				= "blank"
		pitch				= 0
		defaultWidth			= 0
		minWidth			= 0
		minSpacing			= 0
		endOfLineCornerKeepoutWidth	= 0
}

Layer		"OD_25" {
		layerNumber			= 18
		maskName			= ""
		visible				= 1
		selectable			= 1
		blink				= 0
		color				= "purple"
		lineStyle			= "solid"
		pattern				= "blank"
		pitch				= 0
		defaultWidth			= 0
		minWidth			= 0
		minSpacing			= 0
		endOfLineCornerKeepoutWidth	= 0
}

Layer		"PP" {
		layerNumber			= 25
		maskName			= ""
		visible				= 1
		selectable			= 1
		blink				= 0
		color				= "red"
		lineStyle			= "solid"
		pattern				= "blank"
		pitch				= 0
		defaultWidth			= 0
		minWidth			= 0
		minSpacing			= 0
		endOfLineCornerKeepoutWidth	= 0
}

Layer		"NP" {
		layerNumber			= 26
		maskName			= ""
		visible				= 1
		selectable			= 1
		blink				= 0
		color				= "white"
		lineStyle			= "solid"
		pattern				= "blank"
		pitch				= 0
		defaultWidth			= 0
		minWidth			= 0
		minSpacing			= 0
		endOfLineCornerKeepoutWidth	= 0
}

Layer		"RPO" {
		layerNumber			= 29
		maskName			= ""
		visible				= 1
		selectable			= 1
		blink				= 0
		color				= "yellow"
		lineStyle			= "solid"
		pattern				= "blank"
		pitch				= 0
		defaultWidth			= 0
		minWidth			= 0
		minSpacing			= 0
		endOfLineCornerKeepoutWidth	= 0
}

Layer		"CO" {
		layerNumber			= 30
		maskName			= ""
		visible				= 1
		selectable			= 1
		blink				= 0
		color				= "blue"
		lineStyle			= "solid"
		pattern				= "blank"
		pitch				= 0
		defaultWidth			= 0
		minWidth			= 0
		minSpacing			= 0
		endOfLineCornerKeepoutWidth	= 0
}

Layer		"M1" {
		layerNumber			= 31
		maskName			= "metal1"
		isDefaultLayer			= 1
		visible				= 1
		selectable			= 1
		blink				= 0
		color				= "blue"
		lineStyle			= "solid"
		pattern				= "dot"
		pitch				= 0.2
		defaultWidth			= 0.09
		minWidth			= 0.09
		minSpacing			= 0.09
		maxWidth			= 12
		stubSpacing			= 0.11
		stubThreshold			= 0.105
		endOfLineCornerKeepoutWidth	= 0.035
		maxSegLenForRC			= 2000
		maxCurrDensity			= 15
		fatTblDimension			= 5
		fatTblThreshold			= (0,0.205,0.425,1.505,4.505)
		fatTblParallelLength		= (0,0.385,0.425,1.505,4.505)
		fatTblSpacing			= (0.09,0.11,0.16,0.5,1.5,
						   0.11,0.11,0.16,0.5,1.5,
						   0.16,0.16,0.16,0.5,1.5,
						   0.5,0.5,0.5,0.5,1.5,
						   1.5,1.5,1.5,1.5,1.5)
		minArea				= 0.042
		minEnclosedArea			= 0.2
		maxNumMinEdge			= 1
		minEdgeLength			= 0.09
		endOfLineSideKeepoutLength	= 0.11
		unitMinResistance               = 0.1600000
                unitNomResistance               = 0.1600000
                unitMaxResistance               = 0.1600000
                unitMinCapacitance              = 0.0002611
                unitNomCapacitance              = 0.0002611
                unitMaxCapacitance              = 0.0002611
                unitMinSideWallCap              = 0.0000350
                unitNomSideWallCap              = 0.0000350
                unitMaxSideWallCap              = 0.0000350
                unitMinChannelCap               = 0.0000809
                unitNomChannelCap               = 0.0000809
                unitMaxChannelCap               = 0.0000809
                unitMinChannelSideCap           = 0.0000184
                unitNomChannelSideCap           = 0.0000184
                unitMaxChannelSideCap           = 0.0000184
}

Layer		"M2" {
		layerNumber			= 32
		maskName			= "metal2"
		isDefaultLayer			= 1
		visible				= 1
		selectable			= 1
		blink				= 0
		color				= "cyan"
		lineStyle			= "solid"
		pattern				= "dot"
		pitch				= 0.2
		defaultWidth			= 0.1
		minWidth			= 0.1
		minSpacing			= 0.1
		maxWidth			= 12
		stubSpacing			= 0.12
		stubThreshold			= 0.115
		endOfLineCornerKeepoutWidth	= 0.035
		maxSegLenForRC			= 2000
		maxCurrDensity			= 19
		fatTblDimension			= 5
		fatTblThreshold			= (0,0.205,0.405,1.505,4.505)
		fatTblParallelLength		= (0,0.385,0.405,1.505,4.505)
		fatTblSpacing			= (0.1,0.12,0.16,0.5,1.5,
						   0.12,0.12,0.16,0.5,1.5,
						   0.16,0.16,0.16,0.5,1.5,
						   0.5,0.5,0.5,0.5,1.5,
						   1.5,1.5,1.5,1.5,1.5)
		minArea				= 0.052
		minEnclosedArea			= 0.2
		maxNumMinEdge			= 1
		minEdgeLength			= 0.1
		endOfLineSideKeepoutLength	= 0.12
		unitMinResistance               = 0.1400000
                unitNomResistance               = 0.1400000
                unitMaxResistance               = 0.1400000
                unitMinCapacitance              = 0.0000766
                unitNomCapacitance              = 0.0000766
                unitMaxCapacitance              = 0.0000766
                unitMinSideWallCap              = 0.0000185
                unitNomSideWallCap              = 0.0000185
                unitMaxSideWallCap              = 0.0000185
                unitMinChannelCap               = 0.0000459
                unitNomChannelCap               = 0.0000459
                unitMaxChannelCap               = 0.0000459
                unitMinChannelSideCap           = 0.0000154
                unitNomChannelSideCap           = 0.0000154
                unitMaxChannelSideCap           = 0.0000154
}

Layer		"M3" {
		layerNumber			= 33
		maskName			= "metal3"
		isDefaultLayer			= 1
		visible				= 1
		selectable			= 1
		blink				= 0
		color				= "green"
		lineStyle			= "solid"
		pattern				= "dot"
		pitch				= 0.2
		defaultWidth			= 0.1
		minWidth			= 0.1
		minSpacing			= 0.1
		maxWidth			= 12
		stubSpacing			= 0.12
		stubThreshold			= 0.115
		endOfLineCornerKeepoutWidth	= 0.035
		maxSegLenForRC			= 2000
		maxCurrDensity			= 19
		fatTblDimension			= 5
		fatTblThreshold			= (0,0.205,0.405,1.505,4.505)
		fatTblParallelLength		= (0,0.385,0.405,1.505,4.505)
		fatTblSpacing			= (0.1,0.12,0.16,0.5,1.5,
						   0.12,0.12,0.16,0.5,1.5,
						   0.16,0.16,0.16,0.5,1.5,
						   0.5,0.5,0.5,0.5,1.5,
						   1.5,1.5,1.5,1.5,1.5)
		minArea				= 0.052
		minEnclosedArea			= 0.2
		maxNumMinEdge			= 1
		minEdgeLength			= 0.1
		endOfLineSideKeepoutLength	= 0.12
		unitMinResistance               = 0.1400000
                unitNomResistance               = 0.1400000
                unitMaxResistance               = 0.1400000
                unitMinCapacitance              = 0.0000418
                unitNomCapacitance              = 0.0000418
                unitMaxCapacitance              = 0.0000418
                unitMinSideWallCap              = 0.0000146
                unitNomSideWallCap              = 0.0000146
                unitMaxSideWallCap              = 0.0000146
                unitMinChannelCap               = 0.0000307
                unitNomChannelCap               = 0.0000307
                unitMaxChannelCap               = 0.0000307
                unitMinChannelSideCap           = 0.0000133
                unitNomChannelSideCap           = 0.0000133
                unitMaxChannelSideCap           = 0.0000133
}

Layer		"M4" {
		layerNumber			= 34
		maskName			= "metal4"
		isDefaultLayer			= 1
		visible				= 1
		selectable			= 1
		blink				= 0
		color				= "magenta"
		lineStyle			= "solid"
		pattern				= "dot"
		pitch				= 0.2
		defaultWidth			= 0.1
		minWidth			= 0.1
		minSpacing			= 0.1
		maxWidth			= 12
		stubSpacing			= 0.12
		stubThreshold			= 0.115
		endOfLineCornerKeepoutWidth	= 0.035
		maxSegLenForRC			= 2000
		maxCurrDensity			= 19
		fatTblDimension			= 5
		fatTblThreshold			= (0,0.205,0.405,1.505,4.505)
		fatTblParallelLength		= (0,0.385,0.405,1.505,4.505)
		fatTblSpacing			= (0.1,0.12,0.16,0.5,1.5,
						   0.12,0.12,0.16,0.5,1.5,
						   0.16,0.16,0.16,0.5,1.5,
						   0.5,0.5,0.5,0.5,1.5,
						   1.5,1.5,1.5,1.5,1.5)
		minArea				= 0.052
		minEnclosedArea			= 0.2
		maxNumMinEdge			= 1
		minEdgeLength			= 0.1
		endOfLineSideKeepoutLength	= 0.12
		unitMinResistance               = 0.1400000
                unitNomResistance               = 0.1400000
                unitMaxResistance               = 0.1400000
                unitMinCapacitance              = 0.0000288
                unitNomCapacitance              = 0.0000288
                unitMaxCapacitance              = 0.0000288
                unitMinSideWallCap              = 0.0000131
                unitNomSideWallCap              = 0.0000131
                unitMaxSideWallCap              = 0.0000131
                unitMinChannelCap               = 0.0000230
                unitNomChannelCap               = 0.0000230
                unitMaxChannelCap               = 0.0000230
                unitMinChannelSideCap           = 0.0000123
                unitNomChannelSideCap           = 0.0000123
                unitMaxChannelSideCap           = 0.0000123
}

Layer		"M5" {
		layerNumber			= 35
		maskName			= "metal5"
		isDefaultLayer			= 1
		visible				= 1
		selectable			= 1
		blink				= 0
		color				= "purple"
		lineStyle			= "solid"
		pattern				= "dot"
		pitch				= 0.2
		defaultWidth			= 0.1
		minWidth			= 0.1
		minSpacing			= 0.1
		maxWidth			= 12
		stubSpacing			= 0.12
		stubThreshold			= 0.115
		endOfLineCornerKeepoutWidth	= 0.035
		maxSegLenForRC			= 2000
		maxCurrDensity			= 19
		fatTblDimension			= 5
		fatTblThreshold			= (0,0.205,0.405,1.505,4.505)
		fatTblParallelLength		= (0,0.385,0.405,1.505,4.505)
		fatTblSpacing			= (0.1,0.12,0.16,0.5,1.5,
						   0.12,0.12,0.16,0.5,1.5,
						   0.16,0.16,0.16,0.5,1.5,
						   0.5,0.5,0.5,0.5,1.5,
						   1.5,1.5,1.5,1.5,1.5)
		minArea				= 0.052
		minEnclosedArea			= 0.2
		maxNumMinEdge			= 1
		minEdgeLength			= 0.1
		endOfLineSideKeepoutLength	= 0.12
		unitMinResistance               = 0.1400000
                unitNomResistance               = 0.1400000
                unitMaxResistance               = 0.1400000
                unitMinCapacitance              = 0.0000219
                unitNomCapacitance              = 0.0000219
                unitMaxCapacitance              = 0.0000219
                unitMinSideWallCap              = 0.0000122
                unitNomSideWallCap              = 0.0000122
                unitMaxSideWallCap              = 0.0000122
                unitMinChannelCap               = 0.0000184
                unitNomChannelCap               = 0.0000184
                unitMaxChannelCap               = 0.0000184
                unitMinChannelSideCap           = 0.0000117
                unitNomChannelSideCap           = 0.0000117
                unitMaxChannelSideCap           = 0.0000117
}

Layer		"M6" {
		layerNumber			= 36
		maskName			= "metal6"
		isDefaultLayer			= 1
		visible				= 1
		selectable			= 1
		blink				= 0
		color				= "red"
		lineStyle			= "solid"
		pattern				= "dot"
		pitch				= 0.2
		defaultWidth			= 0.1
		minWidth			= 0.1
		minSpacing			= 0.1
		maxWidth			= 12
		stubSpacing			= 0.12
		stubThreshold			= 0.115
		endOfLineCornerKeepoutWidth	= 0.035
		maxSegLenForRC			= 2000
		maxCurrDensity			= 19
		fatTblDimension			= 5
		fatTblThreshold			= (0,0.205,0.405,1.505,4.505)
		fatTblParallelLength		= (0,0.385,0.405,1.505,4.505)
		fatTblSpacing			= (0.1,0.12,0.16,0.5,1.5,
						   0.12,0.12,0.16,0.5,1.5,
						   0.16,0.16,0.16,0.5,1.5,
						   0.5,0.5,0.5,0.5,1.5,
						   1.5,1.5,1.5,1.5,1.5)
		minArea				= 0.052
		minEnclosedArea			= 0.2
		maxNumMinEdge			= 1
		minEdgeLength			= 0.1
		endOfLineSideKeepoutLength	= 0.12
		unitMinResistance               = 0.1400000
                unitNomResistance               = 0.1400000
                unitMaxResistance               = 0.1400000
                unitMinCapacitance              = 0.0000177
                unitNomCapacitance              = 0.0000177
                unitMaxCapacitance              = 0.0000177
                unitMinSideWallCap              = 0.0000119
                unitNomSideWallCap              = 0.0000119
                unitMaxSideWallCap              = 0.0000119
                unitMinChannelCap               = 0.0000154
                unitNomChannelCap               = 0.0000154
                unitMaxChannelCap               = 0.0000154
                unitMinChannelSideCap           = 0.0000115
                unitNomChannelSideCap           = 0.0000115
                unitMaxChannelSideCap           = 0.0000115
}

Layer		"M7" {
		layerNumber			= 37
		maskName			= "metal7"
		isDefaultLayer			= 1
		visible				= 1
		selectable			= 1
		blink				= 0
		color				= "white"
		lineStyle			= "solid"
		pattern				= "dot"
		pitch				= 0.8
		defaultWidth			= 0.4
		minWidth			= 0.4
		minSpacing			= 0.4
		maxWidth			= 12
		endOfLineCornerKeepoutWidth	= 0
		maxSegLenForRC			= 2000
		maxCurrDensity			= 81
		fatTblDimension			= 3
		fatTblThreshold			= (0,1.505,4.505)
		fatTblParallelLength		= (0,1.505,4.505)
		fatTblSpacing			= (0.4,0.5,1.5,
						   0.5,0.5,1.5,
						   1.5,1.5,1.5)
		minArea				= 0.565
		minEnclosedArea			= 0.565
		maxNumMinEdge			= 1
		minEdgeLength			= 0.4
		unitMinResistance               = 0.0220000
                unitNomResistance               = 0.0220000
                unitMaxResistance               = 0.0220000
                unitMinCapacitance              = 0.0000149
                unitNomCapacitance              = 0.0000149
                unitMaxCapacitance              = 0.0000149
                unitMinSideWallCap              = 0.0000123
                unitNomSideWallCap              = 0.0000123
                unitMaxSideWallCap              = 0.0000123
                unitMinChannelCap               = 0.0000132
                unitNomChannelCap               = 0.0000132
                unitMaxChannelCap               = 0.0000132
                unitMinChannelSideCap           = 0.0000119
                unitNomChannelSideCap           = 0.0000119
                unitMaxChannelSideCap           = 0.0000119
}

Layer		"M8" {
		layerNumber			= 38
		maskName			= "metal8"
		isDefaultLayer			= 1
		visible				= 1
		selectable			= 1
		blink				= 0
		color				= "yellow"
		lineStyle			= "solid"
		pattern				= "dot"
		pitch				= 0.8
		defaultWidth			= 0.4
		minWidth			= 0.4
		minSpacing			= 0.4
		maxWidth			= 12
		endOfLineCornerKeepoutWidth	= 0
		maxSegLenForRC			= 2000
		maxCurrDensity			= 81
		fatTblDimension			= 3
		fatTblThreshold			= (0,1.505,4.505)
		fatTblParallelLength		= (0,1.505,4.505)
		fatTblSpacing			= (0.4,0.5,1.5,
						   0.5,0.5,1.5,
						   1.5,1.5,1.5)
		minArea				= 0.565
		minEnclosedArea			= 0.565
		maxNumMinEdge			= 1
		minEdgeLength			= 0.4
		unitMinResistance               = 0.0220000
                unitNomResistance               = 0.0220000
                unitMaxResistance               = 0.0220000
                unitMinCapacitance              = 0.0000089
                unitNomCapacitance              = 0.0000089
                unitMaxCapacitance              = 0.0000089
                unitMinSideWallCap              = 0.0000170
                unitNomSideWallCap              = 0.0000170
                unitMaxSideWallCap              = 0.0000170
                unitMinChannelCap               = 0.0000081
                unitNomChannelCap               = 0.0000081
                unitMaxChannelCap               = 0.0000081
                unitMinChannelSideCap           = 0.0000163
                unitNomChannelSideCap           = 0.0000163
                unitMaxChannelSideCap           = 0.0000163
}

Layer		"M9" {
		layerNumber			= 39
		maskName			= ""
		visible				= 1
		selectable			= 1
		blink				= 0
		color				= "cyan"
		lineStyle			= "solid"
		pattern				= "blank"
		pitch				= 0
		defaultWidth			= 0
		minWidth			= 0
		minSpacing			= 0
		endOfLineCornerKeepoutWidth	= 0
}

Layer		"VIA1" {
		layerNumber			= 51
		maskName			= "via1"
		isDefaultLayer			= 1
		visible				= 1
		selectable			= 1
		blink				= 0
		color				= "cyan"
		lineStyle			= "solid"
		pattern				= "rectangleX"
		pitch				= 0
		defaultWidth			= 0
		minWidth			= 0
		minSpacing			= 0.13
		cornerMinSpacing		= 0.13
		sameNetMinSpacing		= 0.1
		endOfLineCornerKeepoutWidth	= 0
		maxCurrDensity			= 1.58e+06
		fatTblDimension			= 5
		fatTblThreshold			= (0,0.305,0.705,2.005,3.005)
		fatTblExtensionRange		= (0,0.8,0.8,2,5)
		fatTblFatContactNumber		= (1,1,1,1,1)
		fatTblFatContactMinCuts		= (1,2,4,4,4)
		fatTblExtensionContactNumber	= (1,1,1,1,1)
		fatTblExtensionMinCuts		= (1,2,2,2,2)
		enclosedCutNumNeighbor		= 3
		enclosedCutNeighborRange	= 0.14
		enclosedCutToNeighborMinSpacing	= 0.13
}

Layer		"VIA2" {
		layerNumber			= 52
		maskName			= "via2"
		isDefaultLayer			= 1
		visible				= 1
		selectable			= 1
		blink				= 0
		color				= "green"
		lineStyle			= "solid"
		pattern				= "rectangleX"
		pitch				= 0
		defaultWidth			= 0
		minWidth			= 0
		minSpacing			= 0.13
		cornerMinSpacing		= 0.13
		sameNetMinSpacing		= 0.1
		endOfLineCornerKeepoutWidth	= 0
		maxCurrDensity			= 1.58e+06
		fatTblDimension			= 5
		fatTblThreshold			= (0,0.305,0.705,2.005,3.005)
		fatTblExtensionRange		= (0,0.8,0.8,2,5)
		fatTblFatContactNumber		= (2,2,2,2,2)
		fatTblFatContactMinCuts		= (1,2,4,4,4)
		fatTblExtensionContactNumber	= (2,2,2,2,2)
		fatTblExtensionMinCuts		= (1,2,2,2,2)
		enclosedCutNumNeighbor		= 3
		enclosedCutNeighborRange	= 0.14
		enclosedCutToNeighborMinSpacing	= 0.13
}

Layer		"VIA3" {
		layerNumber			= 53
		maskName			= "via3"
		isDefaultLayer			= 1
		visible				= 1
		selectable			= 1
		blink				= 0
		color				= "magenta"
		lineStyle			= "solid"
		pattern				= "rectangleX"
		pitch				= 0
		defaultWidth			= 0
		minWidth			= 0
		minSpacing			= 0.13
		cornerMinSpacing		= 0.13
		sameNetMinSpacing		= 0.1
		endOfLineCornerKeepoutWidth	= 0
		maxCurrDensity			= 1.58e+06
		fatTblDimension			= 5
		fatTblThreshold			= (0,0.305,0.705,2.005,3.005)
		fatTblExtensionRange		= (0,0.8,0.8,2,5)
		fatTblFatContactNumber		= (3,3,3,3,3)
		fatTblFatContactMinCuts		= (1,2,4,4,4)
		fatTblExtensionContactNumber	= (3,3,3,3,3)
		fatTblExtensionMinCuts		= (1,2,2,2,2)
		enclosedCutNumNeighbor		= 3
		enclosedCutNeighborRange	= 0.14
		enclosedCutToNeighborMinSpacing	= 0.13
}

Layer		"VIA4" {
		layerNumber			= 54
		maskName			= "via4"
		isDefaultLayer			= 1
		visible				= 1
		selectable			= 1
		blink				= 0
		color				= "purple"
		lineStyle			= "solid"
		pattern				= "rectangleX"
		pitch				= 0
		defaultWidth			= 0
		minWidth			= 0
		minSpacing			= 0.13
		cornerMinSpacing		= 0.13
		sameNetMinSpacing		= 0.1
		endOfLineCornerKeepoutWidth	= 0
		maxCurrDensity			= 1.58e+06
		fatTblDimension			= 5
		fatTblThreshold			= (0,0.305,0.705,2.005,3.005)
		fatTblExtensionRange		= (0,0.8,0.8,2,5)
		fatTblFatContactNumber		= (4,4,4,4,4)
		fatTblFatContactMinCuts		= (1,2,4,4,4)
		fatTblExtensionContactNumber	= (4,4,4,4,4)
		fatTblExtensionMinCuts		= (1,2,2,2,2)
		enclosedCutNumNeighbor		= 3
		enclosedCutNeighborRange	= 0.14
		enclosedCutToNeighborMinSpacing	= 0.13
}

Layer		"VIA5" {
		layerNumber			= 55
		maskName			= "via5"
		isDefaultLayer			= 1
		visible				= 1
		selectable			= 1
		blink				= 0
		color				= "red"
		lineStyle			= "solid"
		pattern				= "rectangleX"
		pitch				= 0
		defaultWidth			= 0
		minWidth			= 0
		minSpacing			= 0.13
		cornerMinSpacing		= 0.13
		sameNetMinSpacing		= 0.1
		endOfLineCornerKeepoutWidth	= 0
		maxCurrDensity			= 1.58e+06
		fatTblDimension			= 5
		fatTblThreshold			= (0,0.305,0.705,2.005,3.005)
		fatTblExtensionRange		= (0,0.8,0.8,2,5)
		fatTblFatContactNumber		= (5,5,5,5,5)
		fatTblFatContactMinCuts		= (1,2,4,4,4)
		fatTblExtensionContactNumber	= (5,5,5,5,5)
		fatTblExtensionMinCuts		= (1,2,2,2,2)
		enclosedCutNumNeighbor		= 3
		enclosedCutNeighborRange	= 0.14
		enclosedCutToNeighborMinSpacing	= 0.13
}

Layer		"VIA6" {
		layerNumber			= 56
		maskName			= "via6"
		isDefaultLayer			= 1
		visible				= 1
		selectable			= 1
		blink				= 0
		color				= "white"
		lineStyle			= "solid"
		pattern				= "rectangleX"
		pitch				= 0
		defaultWidth			= 0
		minWidth			= 0
		minSpacing			= 0.34
		endOfLineCornerKeepoutWidth	= 0
		maxCurrDensity			= 2.14748e+06
		fatTblDimension			= 6
		fatTblThreshold			= (0,0.305,0.705,1.805,2.005,3.005)
		fatTblExtensionRange		= (0,0.8,0.8,0.8,2,5)
		fatTblFatContactNumber		= (6,6,6,6,6,6)
		fatTblFatContactMinCuts		= (1,2,4,4,4,4)
		fatTblExtensionContactNumber	= (6,6,6,6,6,6)
		fatTblExtensionMinCuts		= (1,2,2,2,2,2)
		enclosedCutNumNeighbor		= 3
		enclosedCutNeighborRange	= 0.56
		enclosedCutToNeighborMinSpacing	= 0.54
}

Layer		"VIA7" {
		layerNumber			= 57
		maskName			= "via7"
		isDefaultLayer			= 1
		visible				= 1
		selectable			= 1
		blink				= 0
		color				= "yellow"
		lineStyle			= "solid"
		pattern				= "rectangleX"
		pitch				= 0
		defaultWidth			= 0
		minWidth			= 0
		minSpacing			= 0.34
		endOfLineCornerKeepoutWidth	= 0
		maxCurrDensity			= 2.14748e+06
		fatTblDimension			= 6
		fatTblThreshold			= (0,0.305,0.705,1.805,2.005,3.005)
		fatTblExtensionRange		= (0,0.8,0.8,0.8,2,5)
		fatTblFatContactNumber		= (7,7,7,7,7,7)
		fatTblFatContactMinCuts		= (1,2,4,4,4,4)
		fatTblExtensionContactNumber	= (7,7,7,7,7,7)
		fatTblExtensionMinCuts		= (1,2,2,2,2,2)
		enclosedCutNumNeighbor		= 3
		enclosedCutNeighborRange	= 0.56
		enclosedCutToNeighborMinSpacing	= 0.54
}

Layer		"VIA8" {
		layerNumber			= 58
		maskName			= ""
		visible				= 1
		selectable			= 1
		blink				= 0
		color				= "purple"
		lineStyle			= "solid"
		pattern				= "blank"
		pitch				= 0
		defaultWidth			= 0
		minWidth			= 0
		minSpacing			= 0
		endOfLineCornerKeepoutWidth	= 0
}

Layer		"ARTISCAN" {
		layerNumber			= 63
		maskName			= ""
		visible				= 1
		selectable			= 1
		blink				= 0
		color				= "red"
		lineStyle			= "solid"
		pattern				= "blank"
		pitch				= 0
		defaultWidth			= 0
		minWidth			= 0
		minSpacing			= 0
		endOfLineCornerKeepoutWidth	= 0
}

Layer		"VTDN" {
		layerNumber			= 66
		maskName			= ""
		visible				= 1
		selectable			= 1
		blink				= 0
		color				= "green"
		lineStyle			= "solid"
		pattern				= "blank"
		pitch				= 0
		defaultWidth			= 0
		minWidth			= 0
		minSpacing			= 0
		endOfLineCornerKeepoutWidth	= 0
}

Layer		"VTH_N" {
		layerNumber			= 67
		maskName			= ""
		visible				= 1
		selectable			= 1
		blink				= 0
		color				= "magenta"
		lineStyle			= "solid"
		pattern				= "blank"
		pitch				= 0
		defaultWidth			= 0
		minWidth			= 0
		minSpacing			= 0
		endOfLineCornerKeepoutWidth	= 0
}

Layer		"VTH_P" {
		layerNumber			= 68
		maskName			= ""
		visible				= 1
		selectable			= 1
		blink				= 0
		color				= "purple"
		lineStyle			= "solid"
		pattern				= "blank"
		pitch				= 0
		defaultWidth			= 0
		minWidth			= 0
		minSpacing			= 0
		endOfLineCornerKeepoutWidth	= 0
}

Layer		"AP" {
		layerNumber			= 74
		maskName			= ""
		visible				= 1
		selectable			= 1
		blink				= 0
		color				= "white"
		lineStyle			= "solid"
		pattern				= "blank"
		pitch				= 0
		defaultWidth			= 0
		minWidth			= 0
		minSpacing			= 0
		endOfLineCornerKeepoutWidth	= 0
}

Layer		"CB" {
		layerNumber			= 76
		maskName			= ""
		visible				= 1
		selectable			= 1
		blink				= 0
		color				= "yellow"
		lineStyle			= "solid"
		pattern				= "blank"
		pitch				= 0
		defaultWidth			= 0
		minWidth			= 0
		minSpacing			= 0
		endOfLineCornerKeepoutWidth	= 0
}

Layer		"RV" {
		layerNumber			= 85
		maskName			= ""
		visible				= 1
		selectable			= 1
		blink				= 0
		color				= "blue"
		lineStyle			= "solid"
		pattern				= "blank"
		pitch				= 0
		defaultWidth			= 0
		minWidth			= 0
		minSpacing			= 0
		endOfLineCornerKeepoutWidth	= 0
}

Layer		"CB2" {
		layerNumber			= 86
		maskName			= ""
		visible				= 1
		selectable			= 1
		blink				= 0
		color				= "cyan"
		lineStyle			= "solid"
		pattern				= "blank"
		pitch				= 0
		defaultWidth			= 0
		minWidth			= 0
		minSpacing			= 0
		endOfLineCornerKeepoutWidth	= 0
}

Layer		"FW" {
		layerNumber			= 95
		maskName			= ""
		visible				= 1
		selectable			= 1
		blink				= 0
		color				= "green"
		lineStyle			= "solid"
		pattern				= "blank"
		pitch				= 0
		defaultWidth			= 0
		minWidth			= 0
		minSpacing			= 0
		endOfLineCornerKeepoutWidth	= 0
}

Layer		"PW_TEXT_BASE0" {
		layerNumber			= 97
		maskName			= ""
		visible				= 1
		selectable			= 1
		blink				= 0
		color				= "green"
		lineStyle			= "solid"
		pattern				= "blank"
		pitch				= 0
		defaultWidth			= 0
		minWidth			= 0
		minSpacing			= 0
		endOfLineCornerKeepoutWidth	= 0
}

LayerDataType		"PW_TEXT" {
		layerNumber			= 97
		dataTypeNumber			= 20
		visible				= 1
		selectable			= 1
		blink				= 0
		color				= "white"
		lineStyle			= "solid"
		pattern				= "blank"
}

Layer		"LDDBLK" {
		layerNumber			= 104
		maskName			= ""
		visible				= 1
		selectable			= 1
		blink				= 0
		color				= "magenta"
		lineStyle			= "solid"
		pattern				= "blank"
		pitch				= 0
		defaultWidth			= 0
		minWidth			= 0
		minSpacing			= 0
		endOfLineCornerKeepoutWidth	= 0
}

Layer		"OVERLAP" {
		layerNumber			= 107
		maskName			= ""
		visible				= 1
		selectable			= 1
		blink				= 0
		color				= "blue"
		lineStyle			= "solid"
		pattern				= "blank"
		pitch				= 0
		defaultWidth			= 0
		minWidth			= 0
		minSpacing			= 0
		endOfLineCornerKeepoutWidth	= 0
}

Layer		"prBoundary" {
		layerNumber			= 108
		maskName			= ""
		visible				= 1
		selectable			= 1
		blink				= 0
		color				= "cyan"
		lineStyle			= "solid"
		pattern				= "blank"
		pitch				= 0
		defaultWidth			= 0
		minWidth			= 0
		minSpacing			= 0
		endOfLineCornerKeepoutWidth	= 0
}

Layer		"LMARK" {
		layerNumber			= 109
		maskName			= ""
		visible				= 1
		selectable			= 1
		blink				= 0
		color				= "purple"
		lineStyle			= "solid"
		pattern				= "blank"
		pitch				= 0
		defaultWidth			= 0
		minWidth			= 0
		minSpacing			= 0
		endOfLineCornerKeepoutWidth	= 0
}

Layer		"PSUB2" {
		layerNumber			= 111
		maskName			= ""
		visible				= 1
		selectable			= 1
		blink				= 0
		color				= "magenta"
		lineStyle			= "solid"
		pattern				= "blank"
		pitch				= 0
		defaultWidth			= 0
		minWidth			= 0
		minSpacing			= 0
		endOfLineCornerKeepoutWidth	= 0
}

Layer		"RPDMY" {
		layerNumber			= 115
		maskName			= ""
		visible				= 1
		selectable			= 1
		blink				= 0
		color				= "purple"
		lineStyle			= "solid"
		pattern				= "blank"
		pitch				= 0
		defaultWidth			= 0
		minWidth			= 0
		minSpacing			= 0
		endOfLineCornerKeepoutWidth	= 0
}

Layer		"RHDMY" {
		layerNumber			= 117
		maskName			= ""
		visible				= 1
		selectable			= 1
		blink				= 0
		color				= "red"
		lineStyle			= "solid"
		pattern				= "blank"
		pitch				= 0
		defaultWidth			= 0
		minWidth			= 0
		minSpacing			= 0
		endOfLineCornerKeepoutWidth	= 0
}

Layer		"DIODMY" {
		layerNumber			= 119
		maskName			= ""
		visible				= 1
		selectable			= 1
		blink				= 0
		color				= "white"
		lineStyle			= "solid"
		pattern				= "blank"
		pitch				= 0
		defaultWidth			= 0
		minWidth			= 0
		minSpacing			= 0
		endOfLineCornerKeepoutWidth	= 0
}

Layer		"SDI" {
		layerNumber			= 122
		maskName			= ""
		visible				= 1
		selectable			= 1
		blink				= 0
		color				= "yellow"
		lineStyle			= "solid"
		pattern				= "blank"
		pitch				= 0
		defaultWidth			= 0
		minWidth			= 0
		minSpacing			= 0
		endOfLineCornerKeepoutWidth	= 0
}

Layer		"M1_TEXT" {
		layerNumber			= 131
		maskName			= ""
		visible				= 1
		selectable			= 1
		blink				= 0
		color				= "magenta"
		lineStyle			= "solid"
		pattern				= "blank"
		pitch				= 0
		defaultWidth			= 0
		minWidth			= 0
		minSpacing			= 0
		endOfLineCornerKeepoutWidth	= 0
}

Layer		"M2_TEXT" {
		layerNumber			= 132
		maskName			= ""
		visible				= 1
		selectable			= 1
		blink				= 0
		color				= "purple"
		lineStyle			= "solid"
		pattern				= "blank"
		pitch				= 0
		defaultWidth			= 0
		minWidth			= 0
		minSpacing			= 0
		endOfLineCornerKeepoutWidth	= 0
}

Layer		"M3_TEXT" {
		layerNumber			= 133
		maskName			= ""
		visible				= 1
		selectable			= 1
		blink				= 0
		color				= "red"
		lineStyle			= "solid"
		pattern				= "blank"
		pitch				= 0
		defaultWidth			= 0
		minWidth			= 0
		minSpacing			= 0
		endOfLineCornerKeepoutWidth	= 0
}

Layer		"M4_TEXT" {
		layerNumber			= 134
		maskName			= ""
		visible				= 1
		selectable			= 1
		blink				= 0
		color				= "white"
		lineStyle			= "solid"
		pattern				= "blank"
		pitch				= 0
		defaultWidth			= 0
		minWidth			= 0
		minSpacing			= 0
		endOfLineCornerKeepoutWidth	= 0
}

Layer		"M5_TEXT" {
		layerNumber			= 135
		maskName			= ""
		visible				= 1
		selectable			= 1
		blink				= 0
		color				= "yellow"
		lineStyle			= "solid"
		pattern				= "blank"
		pitch				= 0
		defaultWidth			= 0
		minWidth			= 0
		minSpacing			= 0
		endOfLineCornerKeepoutWidth	= 0
}

Layer		"M6_TEXT" {
		layerNumber			= 136
		maskName			= ""
		visible				= 1
		selectable			= 1
		blink				= 0
		color				= "blue"
		lineStyle			= "solid"
		pattern				= "blank"
		pitch				= 0
		defaultWidth			= 0
		minWidth			= 0
		minSpacing			= 0
		endOfLineCornerKeepoutWidth	= 0
}

Layer		"M7_TEXT" {
		layerNumber			= 137
		maskName			= ""
		visible				= 1
		selectable			= 1
		blink				= 0
		color				= "cyan"
		lineStyle			= "solid"
		pattern				= "blank"
		pitch				= 0
		defaultWidth			= 0
		minWidth			= 0
		minSpacing			= 0
		endOfLineCornerKeepoutWidth	= 0
}

Layer		"M8_TEXT" {
		layerNumber			= 138
		maskName			= ""
		visible				= 1
		selectable			= 1
		blink				= 0
		color				= "green"
		lineStyle			= "solid"
		pattern				= "blank"
		pitch				= 0
		defaultWidth			= 0
		minWidth			= 0
		minSpacing			= 0
		endOfLineCornerKeepoutWidth	= 0
}

Layer		"M9_TEXT" {
		layerNumber			= 139
		maskName			= ""
		visible				= 1
		selectable			= 1
		blink				= 0
		color				= "magenta"
		lineStyle			= "solid"
		pattern				= "blank"
		pitch				= 0
		defaultWidth			= 0
		minWidth			= 0
		minSpacing			= 0
		endOfLineCornerKeepoutWidth	= 0
}

Layer		"ESD2DMY" {
		layerNumber			= 146
		maskName			= ""
		visible				= 1
		selectable			= 1
		blink				= 0
		color				= "blue"
		lineStyle			= "solid"
		pattern				= "blank"
		pitch				= 0
		defaultWidth			= 0
		minWidth			= 0
		minSpacing			= 0
		endOfLineCornerKeepoutWidth	= 0
}

Layer		"ESD3" {
		layerNumber			= 147
		maskName			= ""
		visible				= 1
		selectable			= 1
		blink				= 0
		color				= "cyan"
		lineStyle			= "solid"
		pattern				= "blank"
		pitch				= 0
		defaultWidth			= 0
		minWidth			= 0
		minSpacing			= 0
		endOfLineCornerKeepoutWidth	= 0
}

Layer		"PO_TEXT" {
		layerNumber			= 149
		maskName			= ""
		visible				= 1
		selectable			= 1
		blink				= 0
		color				= "green"
		lineStyle			= "solid"
		pattern				= "blank"
		pitch				= 0
		defaultWidth			= 0
		minWidth			= 0
		minSpacing			= 0
		endOfLineCornerKeepoutWidth	= 0
}

Layer		"VTUL_N" {
		layerNumber			= 151
		maskName			= ""
		visible				= 1
		selectable			= 1
		blink				= 0
		color				= "cyan"
		lineStyle			= "solid"
		pattern				= "blank"
		pitch				= 0
		defaultWidth			= 0
		minWidth			= 0
		minSpacing			= 0
		endOfLineCornerKeepoutWidth	= 0
}

Layer		"VTUL_P" {
		layerNumber			= 152
		maskName			= ""
		visible				= 1
		selectable			= 1
		blink				= 0
		color				= "green"
		lineStyle			= "solid"
		pattern				= "blank"
		pitch				= 0
		defaultWidth			= 0
		minWidth			= 0
		minSpacing			= 0
		endOfLineCornerKeepoutWidth	= 0
}

Layer		"POFUSE" {
		layerNumber			= 156
		maskName			= ""
		visible				= 1
		selectable			= 1
		blink				= 0
		color				= "red"
		lineStyle			= "solid"
		pattern				= "blank"
		pitch				= 0
		defaultWidth			= 0
		minWidth			= 0
		minSpacing			= 0
		endOfLineCornerKeepoutWidth	= 0
}

Layer		"SEALRING" {
		layerNumber			= 162
		maskName			= ""
		visible				= 1
		selectable			= 1
		blink				= 0
		color				= "white"
		lineStyle			= "solid"
		pattern				= "blank"
		pitch				= 0
		defaultWidth			= 0
		minWidth			= 0
		minSpacing			= 0
		endOfLineCornerKeepoutWidth	= 0
}

Layer		"CDUDMY" {
		layerNumber			= 165
		maskName			= ""
		visible				= 1
		selectable			= 1
		blink				= 0
		color				= "yellow"
		lineStyle			= "solid"
		pattern				= "blank"
		pitch				= 0
		defaultWidth			= 0
		minWidth			= 0
		minSpacing			= 0
		endOfLineCornerKeepoutWidth	= 0
}

Layer		"CSRDMY" {
		layerNumber			= 166
		maskName			= ""
		visible				= 1
		selectable			= 1
		blink				= 0
		color				= "blue"
		lineStyle			= "solid"
		pattern				= "blank"
		pitch				= 0
		defaultWidth			= 0
		minWidth			= 0
		minSpacing			= 0
		endOfLineCornerKeepoutWidth	= 0
}

Layer		"TAP" {
		layerNumber			= 187
		maskName			= ""
		visible				= 1
		selectable			= 1
		blink				= 0
		color				= "yellow"
		lineStyle			= "solid"
		pattern				= "blank"
		pitch				= 0
		defaultWidth			= 0
		minWidth			= 0
		minSpacing			= 0
		endOfLineCornerKeepoutWidth	= 0
}

ContactCode	"VIA1_0_HV" {
		contactCodeNumber		= 1
		cutLayer			= "VIA1"
		lowerLayer			= "M1"
		upperLayer			= "M2"
		isDefaultContact		= 1
		cutWidth			= 0.1
		cutHeight			= 0.1
		upperLayerEncWidth		= 0
		upperLayerEncHeight		= 0.04
		lowerLayerEncWidth		= 0.04
		lowerLayerEncHeight		= 0
		minCutSpacing			= 0.1
}

ContactCode	"VIA2_0_VH" {
		contactCodeNumber		= 2
		cutLayer			= "VIA2"
		lowerLayer			= "M2"
		upperLayer			= "M3"
		isDefaultContact		= 1
		cutWidth			= 0.1
		cutHeight			= 0.1
		upperLayerEncWidth		= 0.04
		upperLayerEncHeight		= 0
		lowerLayerEncWidth		= 0
		lowerLayerEncHeight		= 0.04
		minCutSpacing			= 0.1
}

ContactCode	"VIA3_0_HV" {
		contactCodeNumber		= 3
		cutLayer			= "VIA3"
		lowerLayer			= "M3"
		upperLayer			= "M4"
		isDefaultContact		= 1
		cutWidth			= 0.1
		cutHeight			= 0.1
		upperLayerEncWidth		= 0
		upperLayerEncHeight		= 0.04
		lowerLayerEncWidth		= 0.04
		lowerLayerEncHeight		= 0
		minCutSpacing			= 0.1
}

ContactCode	"VIA4_0_VH" {
		contactCodeNumber		= 4
		cutLayer			= "VIA4"
		lowerLayer			= "M4"
		upperLayer			= "M5"
		isDefaultContact		= 1
		cutWidth			= 0.1
		cutHeight			= 0.1
		upperLayerEncWidth		= 0.04
		upperLayerEncHeight		= 0
		lowerLayerEncWidth		= 0
		lowerLayerEncHeight		= 0.04
		minCutSpacing			= 0.1
}

ContactCode	"VIA5_0_HV" {
		contactCodeNumber		= 5
		cutLayer			= "VIA5"
		lowerLayer			= "M5"
		upperLayer			= "M6"
		isDefaultContact		= 1
		cutWidth			= 0.1
		cutHeight			= 0.1
		upperLayerEncWidth		= 0
		upperLayerEncHeight		= 0.04
		lowerLayerEncWidth		= 0.04
		lowerLayerEncHeight		= 0
		minCutSpacing			= 0.1
}

ContactCode	"VIA6_0_VH" {
		contactCodeNumber		= 6
		cutLayer			= "VIA6"
		lowerLayer			= "M6"
		upperLayer			= "M7"
		isDefaultContact		= 1
		cutWidth			= 0.36
		cutHeight			= 0.36
		upperLayerEncWidth		= 0.08
		upperLayerEncHeight		= 0.02
		lowerLayerEncWidth		= 0.02
		lowerLayerEncHeight		= 0.08
		minCutSpacing			= 0.34
}

ContactCode	"VIA7_0_HV" {
		contactCodeNumber		= 7
		cutLayer			= "VIA7"
		lowerLayer			= "M7"
		upperLayer			= "M8"
		isDefaultContact		= 1
		cutWidth			= 0.36
		cutHeight			= 0.36
		upperLayerEncWidth		= 0.02
		upperLayerEncHeight		= 0.08
		lowerLayerEncWidth		= 0.08
		lowerLayerEncHeight		= 0.02
		minCutSpacing			= 0.34
}

ContactCode	"VIA1_V" {
		contactCodeNumber		= 9
		cutLayer			= "VIA1"
		lowerLayer			= "M1"
		upperLayer			= "M2"
		cutWidth			= 0.1
		cutHeight			= 0.1
		upperLayerEncWidth		= 0
		upperLayerEncHeight		= 0.04
		lowerLayerEncWidth		= 0
		lowerLayerEncHeight		= 0.04
		minCutSpacing			= 0.1
}

ContactCode	"VIA1_H" {
		contactCodeNumber		= 10
		cutLayer			= "VIA1"
		lowerLayer			= "M1"
		upperLayer			= "M2"
		cutWidth			= 0.1
		cutHeight			= 0.1
		upperLayerEncWidth		= 0.04
		upperLayerEncHeight		= 0
		lowerLayerEncWidth		= 0.04
		lowerLayerEncHeight		= 0
		minCutSpacing			= 0.1
}

DesignRule	{
		layer1				= "via1Blockage"
		layer2				= "VIA1"
		minSpacing			= 0.13
}

DesignRule	{
		layer1				= "via2Blockage"
		layer2				= "VIA2"
		minSpacing			= 0.13
}

DesignRule	{
		layer1				= "via3Blockage"
		layer2				= "VIA3"
		minSpacing			= 0.13
}

DesignRule	{
		layer1				= "via4Blockage"
		layer2				= "VIA4"
		minSpacing			= 0.13
}

DesignRule	{
		layer1				= "via5Blockage"
		layer2				= "VIA5"
		minSpacing			= 0.13
}

DesignRule	{
		layer1				= "via6Blockage"
		layer2				= "VIA6"
		minSpacing			= 0.34
}

DesignRule	{
		layer1				= "via7Blockage"
		layer2				= "VIA7"
		minSpacing			= 0.34
}

PRRule		{
		rowSpacingTopTop		= 0
		rowSpacingTopBot		= 0
		rowSpacingBotBot		= 0
		abuttableTopTop			= 0
		abuttableTopBot			= 1
		abuttableBotBot			= 0
}
